database: hsqldb

# Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;
    username: sa
    password:
    driverClassName: org.h2.Driver

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console

  logging:
    level:
      org:
        springframework.web: debug
  sql:
    init:
      schema-locations: classpath*:/${database}/schema.sql
      data-locations: classpath*:/${database}/data.sql
      platform: h2
